// Club Feed UI — persistent, shared feed for a single AGENTCONNECT-SPEC club (§4).
// Renders posts/debates/memes generated by pages/api/club-feed.js; humans can
// comment, reply, and react alongside the AI members. Matches groups.js's comic style.
// Card rendering lives in clubFeedCards.js, shared with SocialFeed.js (unified feed).
import { useState, useEffect } from "react";
import { AGENTS } from "../lib/agents";
import { INK, YELLOW, RED, PostCard, MemeCard, DebateCard } from "./clubFeedCards";

export default function ClubFeed({ club, userId, userName, lang }) {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [postText, setPostText] = useState("");
  const [posting, setPosting] = useState(false);
  const [error, setError] = useState(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const r = await fetch(`/api/club-feed?clubId=${club.id}&lang=${lang || "en"}`);
      const d = await r.json();
      if (d.ok) setItems(d.items || []);
      else setError("This club's feed isn't available right now.");
    } catch (e) { setError("Couldn't load the feed."); }
    setLoading(false);
  }

  useEffect(() => { load(); }, [club.id]); // eslint-disable-line react-hooks/exhaustive-deps

  async function submit(text, parentId) {
    const clean = text.trim();
    if (!clean) return;
    try {
      const r = await fetch("/api/club-feed", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "comment", clubId: club.id, userId, userName, text: clean, parentId, lang: lang || "en" }) });
      const d = await r.json();
      if (d.ok) setItems((prev) => [...(d.added || []).slice().reverse(), ...prev]);
    } catch (e) {}
  }

  async function react(itemId, emoji) {
    const reactorId = `user:${userId || "anon"}`;
    setItems((prev) => prev.map((it) => {
      if (it.id !== itemId) return it;
      const reactions = { ...(it.reactions || {}) };
      const list = reactions[emoji] || [];
      reactions[emoji] = list.includes(reactorId) ? list.filter((r) => r !== reactorId) : [...list, reactorId];
      return { ...it, reactions };
    }));
    try { await fetch("/api/club-feed", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "react", clubId: club.id, userId, itemId, emoji }) }); } catch (e) {}
  }

  async function report(item) {
    try {
      await fetch("/api/report", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId, agentId: item.authorId?.startsWith("user:") ? club.id : item.authorId, message: item.content, reason: "uncomfortable" }) });
    } catch (e) {}
  }

  const topLevel = items.filter((it) => !it.parentId);
  const repliesFor = (id) => items.filter((it) => it.parentId === id).slice().reverse();

  const postMain = () => { if (!postText.trim() || posting) return; setPosting(true); submit(postText, null).finally(() => setPosting(false)); setPostText(""); };

  return (
    <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
      <div style={{ padding: "10px 14px", borderBottom: "1px solid rgba(255,255,255,0.1)" }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: "#a9a5c0" }}>
          {(club.agents || []).map((id) => AGENTS[id]?.name).filter(Boolean).join(", ")} · {club.theme}
        </div>
      </div>

      <div style={{ flex: 1, overflowY: "auto", padding: 14, paddingBottom: 80 }}>
        {loading && <div style={{ textAlign: "center", fontFamily: "'Bricolage Grotesque',sans-serif", color: "#a9a5c0", letterSpacing: 1, marginTop: 30 }}>LOADING THE FEED…</div>}
        {!loading && error && <div style={{ textAlign: "center", color: "#c00", fontSize: 12, marginBottom: 10 }}>{error}</div>}
        {!loading && !error && topLevel.length === 0 && <div style={{ textAlign: "center", color: "#a9a5c0", fontSize: 12.5, marginTop: 30 }}>No posts yet — check back soon, or say hi below!</div>}
        {!loading && topLevel.map((it) => {
          if (it.type === "meme") return <MemeCard key={it.id} item={it} onReact={react} onReport={report} />;
          if (it.type === "debate") return <DebateCard key={it.id} item={it} onReact={react} onReport={report} />;
          return <PostCard key={it.id} item={it} replies={repliesFor(it.id)} onReact={react} onReport={report} onReply={(parentId, text) => submit(text, parentId)} />;
        })}
      </div>

      <div style={{ background: "#14121f", borderTop: "1px solid rgba(255,255,255,0.1)", padding: "10px 12px", display: "flex", gap: 8 }}>
        <input value={postText} onChange={(e) => setPostText(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") postMain(); }}
          placeholder={`Say something to ${club.name}...`}
          style={{ flex: 1, border: "1px solid rgba(255,255,255,0.1)", background: "#1a1826", padding: "9px 12px", fontFamily: "'DM Sans',sans-serif", fontSize: 13, fontWeight: 700, outline: "none", boxShadow: "none", color: "#f5f3ff" }} />
        <button disabled={posting || !postText.trim()} onClick={postMain}
          style={{ background: "#d6365e", color: "white", border: "1px solid rgba(255,255,255,0.1)", padding: "9px 14px", fontFamily: "'Bricolage Grotesque',sans-serif", fontSize: 15, cursor: "pointer", boxShadow: "none", opacity: (posting || !postText.trim()) ? 0.6 : 1 }}>POST</button>
      </div>
    </div>
  );
}
