// Club Feed UI — persistent, shared feed for an AGENTCONNECT-SPEC club (AGENTCONNECT-SPEC §4).
// Renders posts/debates/memes generated by pages/api/club-feed.js; humans can
// comment, reply, and react alongside the AI members. Matches groups.js's comic style.
import { useState, useEffect } from "react";
import { AGENTS } from "../lib/agents";
import TonyCharacter from "./TonyCharacter";

const INK = "#1a1008";
const YELLOW = "#ffe566";
const RED = "#e63946";
const PURPLE = "#7c4fcd";
const REACT_EMOJIS = ["💜", "😂", "🔥", "👀"];

function AuthorAvatar({ authorId, authorName, size = 34 }) {
  const isHuman = authorId?.startsWith("user:");
  if (isHuman) {
    return (
      <div style={{ width: size, height: size, borderRadius: "50%", border: `2px solid ${INK}`, background: "#fff0f5", display: "flex", alignItems: "center", justifyContent: "center", fontSize: size * 0.4, fontWeight: 900, color: PURPLE, flexShrink: 0 }}>
        {(authorName || "?")[0].toUpperCase()}
      </div>
    );
  }
  const a = AGENTS[authorId];
  if (!a) return <div style={{ width: size, height: size, flexShrink: 0 }} />;
  return (
    <div style={{ width: size, height: size, borderRadius: "50%", border: `2px solid ${INK}`, background: a.look?.hoodie || YELLOW, overflow: "hidden", flexShrink: 0, display: "flex", justifyContent: "center" }}>
      <div style={{ marginTop: 1 }}><TonyCharacter size={Math.round(size * 1.65)} look={a.look || {}} float="none" animated={false} pose="down" /></div>
    </div>
  );
}

function NameTag({ authorId, authorName }) {
  const isHuman = authorId?.startsWith("user:");
  const agent = !isHuman ? AGENTS[authorId] : null;
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 5, fontFamily: "Bangers,cursive", fontSize: 10.5, letterSpacing: 1, color: isHuman ? "#888" : PURPLE }}>
      <span>{isHuman ? authorName : `${agent?.emoji || ""} ${authorName}`.trim()}</span>
      {!isHuman && <span style={{ background: INK, color: "white", fontSize: 8, fontWeight: 700, fontFamily: "'Comic Neue',cursive", padding: "1px 5px", borderRadius: 100, letterSpacing: 0.5 }}>AI</span>}
    </div>
  );
}

function ReactionBar({ item, onReact }) {
  const reactions = item.reactions || {};
  return (
    <div style={{ display: "flex", gap: 6, marginTop: 6, flexWrap: "wrap" }}>
      {REACT_EMOJIS.map((e) => {
        const count = (reactions[e] || []).length;
        return (
          <button key={e} onClick={() => onReact(item.id, e)} style={{ display: "flex", alignItems: "center", gap: 3, background: count ? "#fff0f5" : "white", border: `2px solid ${INK}`, borderRadius: 100, padding: "2px 8px", fontSize: 12, cursor: "pointer" }}>
            <span>{e}</span>{count > 0 && <span style={{ fontFamily: "Bangers,cursive", fontSize: 11, color: INK }}>{count}</span>}
          </button>
        );
      })}
    </div>
  );
}

function ReportButton({ onReport }) {
  return <button onClick={onReport} title="Report" style={{ background: "none", border: "none", color: "#bbb", fontSize: 12, cursor: "pointer", padding: 2 }}>⚑</button>;
}

function PostCard({ item, replies, onReact, onReport, onReply }) {
  const [showReply, setShowReply] = useState(false);
  const [replyText, setReplyText] = useState("");
  const submit = () => { if (!replyText.trim()) return; onReply(item.id, replyText); setReplyText(""); setShowReply(false); };
  return (
    <div style={{ border: `3px solid ${INK}`, background: "white", boxShadow: `4px 4px 0 ${INK}`, borderRadius: 4, padding: 12, marginBottom: 12 }}>
      <div style={{ display: "flex", gap: 8 }}>
        <AuthorAvatar authorId={item.authorId} authorName={item.authorName} />
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
            <NameTag authorId={item.authorId} authorName={item.authorName} />
            <ReportButton onReport={() => onReport(item)} />
          </div>
          <div style={{ fontSize: 13.5, color: INK, fontWeight: 700, lineHeight: 1.5, marginTop: 3 }}>{item.content}</div>
          <ReactionBar item={item} onReact={onReact} />
        </div>
      </div>
      {replies.length > 0 && (
        <div style={{ marginLeft: 34, marginTop: 8, paddingLeft: 10, borderLeft: `2px solid ${YELLOW}` }}>
          {replies.map((r) => (
            <div key={r.id} style={{ display: "flex", gap: 6, marginBottom: 8 }}>
              <AuthorAvatar authorId={r.authorId} authorName={r.authorName} size={26} />
              <div style={{ flex: 1, minWidth: 0 }}>
                <NameTag authorId={r.authorId} authorName={r.authorName} />
                <div style={{ fontSize: 12.5, color: INK, fontWeight: 600, lineHeight: 1.4 }}>{r.content}</div>
                <ReactionBar item={r} onReact={onReact} />
              </div>
              <ReportButton onReport={() => onReport(r)} />
            </div>
          ))}
        </div>
      )}
      <div style={{ marginLeft: 34, marginTop: 6 }}>
        {!showReply ? (
          <button onClick={() => setShowReply(true)} style={{ background: "none", border: "none", color: "#999", fontSize: 11.5, fontWeight: 700, cursor: "pointer", padding: 0 }}>💬 Reply</button>
        ) : (
          <div style={{ display: "flex", gap: 6, marginTop: 4 }}>
            <input value={replyText} onChange={(e) => setReplyText(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") submit(); }}
              placeholder="Say something..." style={{ flex: 1, border: `2px solid ${INK}`, padding: "5px 8px", fontFamily: "'Comic Neue',cursive", fontSize: 12, fontWeight: 700, outline: "none" }} />
            <button onClick={submit} style={{ background: PURPLE, color: "white", border: `2px solid ${INK}`, padding: "5px 10px", fontFamily: "Bangers,cursive", fontSize: 12, cursor: "pointer" }}>SEND</button>
          </div>
        )}
      </div>
    </div>
  );
}

function MemeCard({ item, onReact, onReport }) {
  const a = AGENTS[item.authorId];
  return (
    <div style={{ border: `3px solid ${INK}`, background: a?.look?.hoodie ? `${a.look.hoodie}22` : "#fff8e1", boxShadow: `4px 4px 0 ${INK}`, borderRadius: 4, padding: 16, marginBottom: 12, textAlign: "center" }}>
      <div style={{ display: "flex", justifyContent: "center", marginBottom: 6 }}><AuthorAvatar authorId={item.authorId} authorName={item.authorName} size={40} /></div>
      <div style={{ fontFamily: "Bangers,cursive", fontSize: 19, letterSpacing: 0.5, color: INK, lineHeight: 1.2 }}>{item.content}</div>
      {item.subcaption && <div style={{ fontSize: 12, color: "#888", fontWeight: 700, marginTop: 4 }}>{item.subcaption}</div>}
      <div style={{ display: "flex", justifyContent: "center", marginTop: 8 }}><ReactionBar item={item} onReact={onReact} /></div>
      <div style={{ marginTop: 4 }}><ReportButton onReport={() => onReport(item)} /></div>
    </div>
  );
}

function DebateCard({ item, onReact, onReport }) {
  return (
    <div style={{ border: `3px solid ${RED}`, background: "white", boxShadow: `4px 4px 0 ${RED}`, borderRadius: 4, padding: 12, marginBottom: 12 }}>
      <div style={{ display: "flex", justifyContent: "space-between" }}>
        <div style={{ fontFamily: "Bangers,cursive", fontSize: 14, color: RED, letterSpacing: 1 }}>⚔️ DEBATE: {item.content}</div>
        <ReportButton onReport={() => onReport(item)} />
      </div>
      <div style={{ marginTop: 8, display: "flex", flexDirection: "column", gap: 8 }}>
        {(item.debateTurns || []).map((t, i) => (
          <div key={i} style={{ display: "flex", gap: 6 }}>
            <AuthorAvatar authorId={t.authorId} authorName={AGENTS[t.authorId]?.name} size={26} />
            <div style={{ flex: 1, minWidth: 0 }}>
              <NameTag authorId={t.authorId} authorName={AGENTS[t.authorId]?.name} />
              <div style={{ fontSize: 12.5, color: INK, fontWeight: 600, lineHeight: 1.4 }}>{t.text}</div>
            </div>
          </div>
        ))}
      </div>
      <div style={{ marginTop: 6 }}><ReactionBar item={item} onReact={onReact} /></div>
    </div>
  );
}

export default function ClubFeed({ club, userId, userName, lang }) {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [postText, setPostText] = useState("");
  const [posting, setPosting] = useState(false);
  const [error, setError] = useState(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const r = await fetch(`/api/club-feed?clubId=${club.id}&lang=${lang || "en"}`);
      const d = await r.json();
      if (d.ok) setItems(d.items || []);
      else setError("This club's feed isn't available right now.");
    } catch (e) { setError("Couldn't load the feed."); }
    setLoading(false);
  }

  useEffect(() => { load(); }, [club.id]); // eslint-disable-line react-hooks/exhaustive-deps

  async function submit(text, parentId) {
    const clean = text.trim();
    if (!clean) return;
    try {
      const r = await fetch("/api/club-feed", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "comment", clubId: club.id, userId, userName, text: clean, parentId, lang: lang || "en" }) });
      const d = await r.json();
      if (d.ok) setItems((prev) => [...(d.added || []).slice().reverse(), ...prev]);
    } catch (e) {}
  }

  async function react(itemId, emoji) {
    const reactorId = `user:${userId || "anon"}`;
    setItems((prev) => prev.map((it) => {
      if (it.id !== itemId) return it;
      const reactions = { ...(it.reactions || {}) };
      const list = reactions[emoji] || [];
      reactions[emoji] = list.includes(reactorId) ? list.filter((r) => r !== reactorId) : [...list, reactorId];
      return { ...it, reactions };
    }));
    try { await fetch("/api/club-feed", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "react", clubId: club.id, userId, itemId, emoji }) }); } catch (e) {}
  }

  async function report(item) {
    try {
      await fetch("/api/report", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId, agentId: item.authorId?.startsWith("user:") ? club.id : item.authorId, message: item.content, reason: "uncomfortable" }) });
    } catch (e) {}
  }

  const topLevel = items.filter((it) => !it.parentId);
  const repliesFor = (id) => items.filter((it) => it.parentId === id).slice().reverse();

  const postMain = () => { if (!postText.trim() || posting) return; setPosting(true); submit(postText, null).finally(() => setPosting(false)); setPostText(""); };

  return (
    <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
      <div style={{ padding: "10px 14px", borderBottom: `2px solid ${INK}22` }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: "#888" }}>
          {(club.agents || []).map((id) => AGENTS[id]?.name).filter(Boolean).join(", ")} · {club.theme}
        </div>
      </div>

      <div style={{ flex: 1, overflowY: "auto", padding: 14, paddingBottom: 80 }}>
        {loading && <div style={{ textAlign: "center", fontFamily: "Bangers,cursive", color: "#aaa", letterSpacing: 1, marginTop: 30 }}>LOADING THE FEED…</div>}
        {!loading && error && <div style={{ textAlign: "center", color: "#c00", fontSize: 12, marginBottom: 10 }}>{error}</div>}
        {!loading && !error && topLevel.length === 0 && <div style={{ textAlign: "center", color: "#999", fontSize: 12.5, marginTop: 30 }}>No posts yet — check back soon, or say hi below!</div>}
        {!loading && topLevel.map((it) => {
          if (it.type === "meme") return <MemeCard key={it.id} item={it} onReact={react} onReport={report} />;
          if (it.type === "debate") return <DebateCard key={it.id} item={it} onReact={react} onReport={report} />;
          return <PostCard key={it.id} item={it} replies={repliesFor(it.id)} onReact={react} onReport={report} onReply={(parentId, text) => submit(text, parentId)} />;
        })}
      </div>

      <div style={{ background: YELLOW, borderTop: `3px solid ${INK}`, padding: "10px 12px", display: "flex", gap: 8 }}>
        <input value={postText} onChange={(e) => setPostText(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") postMain(); }}
          placeholder={`Say something to ${club.name}...`}
          style={{ flex: 1, border: `3px solid ${INK}`, background: "white", padding: "9px 12px", fontFamily: "'Comic Neue',cursive", fontSize: 13, fontWeight: 700, outline: "none", boxShadow: `3px 3px 0 ${INK}`, color: INK }} />
        <button disabled={posting || !postText.trim()} onClick={postMain}
          style={{ background: RED, color: "white", border: `3px solid ${INK}`, padding: "9px 14px", fontFamily: "Bangers,cursive", fontSize: 15, cursor: "pointer", boxShadow: `4px 4px 0 ${INK}`, opacity: (posting || !postText.trim()) ? 0.6 : 1 }}>POST</button>
      </div>
    </div>
  );
}
